### ISSUE TITLE
Custom Color/Image Background 

### ISSUE THREAD

**Issue by JammenTooHard** [ReVancedTeam/revanced-suggestions#64] opened 2022-04-03 20:01 UTC
Add a feature where you can customize the background with preset colors Hex, RGB codes possibly even images,

**Comment by JammenTooHard** [comment] 2022-04-03 20:05
There could be community made themes for it like aliucord as well

**Comment by oSumAtrIX** [comment] 2022-04-03 20:40
Dupe of #18

**Closed by oSumAtrIX** 2022-04-03 20:40 UTC
