### ISSUE TITLE
Add the video queue feature

### ISSUE THREAD

**Issue by diabolo98** [ReVancedTeam/revanced-suggestions#107] opened 2022-05-02 18:52 UTC
On pc we are able to create a video queue of the videos we wanna watch. Unlike a normal playlist like 'Watch Later', the queue feature is only limited to the current session, so when you close the webpage, the queue is gone.

This feature would be great on mobile, it would allow to add multiple recommended videos  directly below the current video transforming it into a temp playlist, instead of having to clutter the watch later playlist.

**Comment by oSumAtrIX** [comment] 2022-05-02 22:34
Dupe of #35

**Closed by oSumAtrIX** 2022-05-02 22:34 UTC

**Comment by diabolo98** [comment] 2022-05-02 23:02
Sorry, my bad.  I did ran a search before posting but for the keyword "playlist" instead of "queue" .
