### ISSUE TITLE
YouTube Comment Search (Revanced Exclusive Feature)

### ISSUE THREAD

**Issue by Cohenl19** [ReVancedTeam/revanced-suggestions#76] opened 2022-04-06 07:00 UTC
I'm one of the unusual ones who'd like a feature that Vanced never had, the ability to search YouTube comments for certain words, and even timestamps. I find it nice to engage with the community on some videos, and being able to search would make it alot easier, plus this exists already on sites like "Hadzy" and "ytcomment.kmcat.uk".

Just a suggestion :)

(posted here as per snuser's request)

**Comment by oSumAtrIX** [comment] 2022-04-06 13:26
Dupe of #24

**Closed by oSumAtrIX** 2022-04-06 13:26 UTC
