### ISSUE TITLE
Compatible with Amazon FireTV

### ISSUE THREAD

**Issue by cybr47** [ReVancedTeam/revanced-suggestions#104] opened 2022-05-01 15:17 UTC
It would be awesome if team can make it compatible with Android TVs. Smart Tube is already available but there are some issues with it.

**Comment by DraakjeYoblama** [comment] 2022-05-01 17:10
Same as #96

**Comment by oSumAtrIX** [comment] 2022-05-01 20:45
Dupe of #96

**Closed by oSumAtrIX** 2022-05-01 20:45 UTC
