### ISSUE TITLE
Stretch to fit instead of zoom to fit

### ISSUE THREAD

**Issue by sargeeva** [ReVancedTeam/revanced-suggestions#88] opened 2022-04-17 16:41 UTC
Having the ability to stretch the video to fit screens with weird aspect ratios *cough* samsung *cough* instead of the weird zoom to fit screen.

**Comment by Relected** [comment] 2022-04-17 16:44
wouldn't that make the video ugly?

**Comment by sargeeva** [comment] 2022-04-17 16:47
Definitely not, and watching with it zoomed to fill the screen makes the video look ugly and not having the black bars cause burn in is ideal.

**Comment by boehs** [comment] 2022-04-17 17:02
Duplicate of #4

**Closed** 2022-04-17 18:18 UTC
